version: '3'
services:
  node-app:
    build: 
      context: .
      dockerfile: Dockerfile
    #image: my-node-img
    ports:
      - "5000:5000"
    container_name: node-app-container  
    #depends_on:
    #  - mongodb

  #mongodb:
  #  image: mongo:latest
  #  ports:
  #    - "27017:27017"
